services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "8080" # Using expose since Nginx will handle the public port
    environment:
    - VUE_APP_GRAPHQL_URL=http://localhost:3000/graphql
    networks:
      - destill-net

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3000" # Exposing for internal communication with Nginx
    environment:
      - MONGO_URI=mongodb://mongodb:27017/destillit
    networks:
      - destill-net
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # No need to expose externally unless needed for local dev tools
    volumes:
      - mongo_data:/data/db
    networks:
      - destill-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Public port 80 for HTTP traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mounting the nginx.conf file
    depends_on:
      - frontend
      - backend
    networks:
      - destill-net

volumes:
  mongo_data:
    driver: local

networks:
  destill-net:

