export const initialPlantForm = {
  plantName: "",
  plantPart: "",
  plantOrigin: "",
  plantBuyDate: "",
  plantProducer: "",
  countryOfOrigin: "",
  harvestDate: "",
  harvestTemperature: null,
  harvestRange: [600, 900],
  harvestStartTime: "10:00",
  harvestEndTime: "15:00",
  plantWeight: null,
  plantState: "",
  dryingTime: null,
  plantAge: null,
  isPlantSoaked: false,
  soakingTime: null,
  weightAfterSoaking: null,
};
