export const initialPlantForm = {
  plantName: "",
  plantPart: "",
  plantOrigin: "",
  plantBuyDate: "",
  plantProducer: "",
  countryOfOrigin: "",
  harvestDate: "",
  harvestTemperature: null,
  harvestRange: [600, 900],
  harvestStartTime: "10:00",
  harvestEndTime: "15:00",
  plantWeight: null,
  availableWeight: null,
  plantState: "",
  dryingTime: null,
  plantAge: null,
  isPlantSoaked: false,
  soakingTime: null,
  weightAfterSoaking: null,
};

export const initialDistillationForm = {
  choosedPlant: {
    id: null,
    name: "",
    part: "",
    availableWeight: null,
    harvestDate: "",
    buyDate: "",
  },
  weightForDistillation: null,
  isPlantSoaked: false,
  soakingTime: null,
  weightAfterSoaking: null,
  isPlantShredded: false,
  distillationType: "",
  distillationDate: "",
  distillationApparatus: "",
  waterForDistillation: null,
  distillationTime: {
    distillationHours: null,
    distillationMinutes: null,
  },
};

export const initialResultsForm = {
  oilAmount: null,
  hydrosolAmount: null,
  hydrosolpH: null,
  oilDescription: "",
  hydrosolDescription: "",
  distillationDate: "",
  distillationType: "",
  waterForDistillation: null,
  choosedPlantName: "",
  choosedPlantPart: "",
  weightForDistillation: null,
};
