 export const defaultArchives = [
      {
        _id: ObjectId("690d20000000000000000101"),
        oilAmount: 12,
        hydrosolAmount: 40,
        hydrosolpH: 6.8,
        oilDescription:
          "Olejek lawendowy o delikatnym, kwiatowym zapachu. Jasny kolor i dobra klarowność.",
        hydrosolDescription:
          "Hydrolat o subtelnym aromacie lawendy, idealny do pielęgnacji skóry.",
        distillationData: {
          weightForDistillation: 30,
          isPlantSoaked: true,
          soakingTime: 3,
          weightAfterSoaking: 44,
          isPlantShredded: false,
          distillationType: "wodno-parowa",
          distillationDate: "2025-10-20",
          distillationApparatus: "Destylator stal nierdzewna - 100l - prąd",
          waterForDistillation: 50,
          distillationTime: { distillationHours: 2, distillationMinutes: 10 },
        },
        distilledPlant: {
          plantName: "lawenda",
          plantPart: "kwiat",
          plantOrigin: "zbiór",
          harvestDate: "2025-10-12T23:00:00.000Z",
          harvestTemperature: 22,
          harvestStartTime: "09:00",
          harvestEndTime: "12:00",
          plantState: "suchy",
          plantAge: 1,
        },
        date: "2025-10-20T00:00:00.000Z",
        userId: ObjectId("690b32b31a18c0d67ce1df44"),
        createdAt: "2025-11-06T10:00:00.000Z",
      },
      {
        _id: ObjectId("690d20000000000000000102"),
        oilAmount: 20,
        hydrosolAmount: 45,
        hydrosolpH: 5.5,
        oilDescription:
          "Świeży, mentolowy zapach, intensywny olejek miętowy wysokiej jakości.",
        hydrosolDescription:
          "Hydrolat miętowy o chłodzącym działaniu i świeżym aromacie.",
        distillationData: {
          weightForDistillation: 70,
          isPlantSoaked: false,
          isPlantShredded: true,
          distillationType: "parowa",
          distillationDate: "2025-10-25",
          distillationApparatus: "Destylator stal nierdzewna - 200l - gaz",
          waterForDistillation: 60,
          distillationTime: { distillationHours: 1, distillationMinutes: 50 },
        },
        distilledPlant: {
          plantName: "mięta pieprzowa",
          plantPart: "ziele",
          plantOrigin: "kupno",
          plantBuyDate: "2025-09-20T23:00:00.000Z",
          plantProducer: "Polskie Zioła",
          countryOfOrigin: "Polska",
          plantState: "suchy",
          plantAge: 2,
        },
        date: "2025-10-25T00:00:00.000Z",
        userId: ObjectId("690b32b31a18c0d67ce1df44"),
        createdAt: "2025-11-06T10:05:00.000Z",
      },
      {
        _id: ObjectId("690d20000000000000000103"),
        oilAmount: 15,
        hydrosolAmount: 55,
        hydrosolpH: 7.2,
        oilDescription:
          "Olejek rozmarynowy o intensywnym, ziołowym zapachu i lekko żółtej barwie.",
        hydrosolDescription:
          "Hydrolat rozmarynowy tonizujący, delikatny aromat i świeży profil.",
        distillationData: {
          weightForDistillation: 50,
          isPlantSoaked: true,
          soakingTime: 2,
          weightAfterSoaking: 72,
          isPlantShredded: false,
          distillationType: "wodna",
          distillationDate: "2025-11-01",
          distillationApparatus: "Destylator miedź - 80l - gaz",
          waterForDistillation: 60,
          distillationTime: { distillationHours: 2, distillationMinutes: 20 },
        },
        distilledPlant: {
          plantName: "rozmaryn",
          plantPart: "ziele",
          plantOrigin: "kupno",
          plantBuyDate: "2025-10-01T23:00:00.000Z",
          plantProducer: "Polski zielarz",
          countryOfOrigin: "Polska",
          plantState: "suchy",
          plantAge: 3,
        },
        date: "2025-11-01T00:00:00.000Z",
        userId: ObjectId("690b32b31a18c0d67ce1df44"),
        createdAt: "2025-11-06T10:10:00.000Z",
      },
      {
        _id: ObjectId("690d20000000000000000104"),
        oilAmount: 18,
        hydrosolAmount: 50,
        hydrosolpH: 6.3,
        oilDescription:
          "Olejek tymiankowy o ciepłym, korzennym zapachu. Bardzo aromatyczny.",
        hydrosolDescription:
          "Hydrolat o intensywnym aromacie tymianku, działa antybakteryjnie.",
        distillationData: {
          weightForDistillation: 60,
          isPlantSoaked: false,
          isPlantShredded: true,
          distillationType: "wodno-parowa",
          distillationDate: "2025-10-29",
          distillationApparatus: "Destylator stal nierdzewna - 200l - gaz",
          waterForDistillation: 55,
          distillationTime: { distillationHours: 1, distillationMinutes: 45 },
        },
        distilledPlant: {
          plantName: "tymianek",
          plantPart: "ziele",
          plantOrigin: "kupno",
          plantBuyDate: "2025-10-15T23:00:00.000Z",
          plantProducer: "Zioła Mazowsze",
          countryOfOrigin: "Polska",
          plantState: "suchy",
          plantAge: 1,
        },
        date: "2025-10-29T00:00:00.000Z",
        userId: ObjectId("690b32b31a18c0d67ce1df44"),
        createdAt: "2025-11-06T10:15:00.000Z",
      },
      {
        _id: ObjectId("690d20000000000000000105"),
        oilAmount: 10,
        hydrosolAmount: 45,
        hydrosolpH: 5.9,
        oilDescription:
          "Delikatny olejek melisowy o cytrusowym aromacie i jasnym odcieniu.",
        hydrosolDescription:
          "Hydrolat melisowy – łagodny, odprężający zapach, do pielęgnacji skóry.",
        distillationData: {
          weightForDistillation: 40,
          isPlantSoaked: true,
          soakingTime: 3,
          weightAfterSoaking: 58,
          isPlantShredded: false,
          distillationType: "parowa",
          distillationDate: "2025-11-03",
          distillationApparatus: "Destylator stal nierdzewna - 100l - prąd",
          waterForDistillation: 50,
          distillationTime: { distillationHours: 1, distillationMinutes: 30 },
        },
        distilledPlant: {
          plantName: "melisa",
          plantPart: "ziele",
          plantOrigin: "kupno",
          plantBuyDate: "2025-10-02T23:00:00.000Z",
          plantProducer: "Herbafarm",
          countryOfOrigin: "Polska",
          plantState: "podsuszony",
          dryingTime: 36,
        },
        date: "2025-11-03T00:00:00.000Z",
        userId: ObjectId("690b32b31a18c0d67ce1df44"),
        createdAt: "2025-11-06T10:20:00.000Z",
      },
    ];